# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as ec


class TestRegisteraccount():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registeraccount(self):
    self.driver.get("http://portal.dev.getzense.com/")
    # wait for element and click #
    signupbutton = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.LINK_TEXT, "Sign up")))
    signupbutton.click()
    ##############################
    # wait for element and click #
    elementid = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.ID, "email")))
    elementid.click()
    ##############################

    ###### First Account #########
    self.driver.find_element(By.ID, "email").send_keys("elizabethfreddie08@freddiemac.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Elizabeth1234=")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("Elizabeth1234=")
    self.driver.find_element(By.ID, "country_code").click()
    dropdown = self.driver.find_element(By.ID, "country_code")
    dropdown.find_element(By.XPATH, "//option[. = '(+1) US']").click()
    self.driver.find_element(By.ID, "phone_number").click()
    self.driver.find_element(By.ID, "phone_number").send_keys("(666) 666-6666")
    self.driver.find_element(By.ID, "registerForm").click()
    self.driver.find_element(By.NAME, "terms").click()
    self.driver.find_element(By.ID, "submit").click()
    # wait for element and click #
    signuplink = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.LINK_TEXT, "Join Zense")))
    signuplink.click()
    ##############################
  # wait for element and click #
    elementid = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.ID, "email")))
    elementid.click()
    ##############################
    
    ###### Second Account #########
    self.driver.find_element(By.ID, "email").send_keys("andyfreddie08@freddiemac.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Andy1234=")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("Andy1234=")
    self.driver.find_element(By.ID, "country_code").click()
    dropdown = self.driver.find_element(By.ID, "country_code")
    dropdown.find_element(By.XPATH, "//option[. = '(+1) US']").click()
    self.driver.find_element(By.ID, "phone_number").click()
    self.driver.find_element(By.ID, "phone_number").send_keys("(555) 333-3333")
    self.driver.find_element(By.ID, "registerForm").click()
    self.driver.find_element(By.NAME, "terms").click()
    self.driver.find_element(By.ID, "submit").click()
    # wait for element and click #
    signuplink = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.LINK_TEXT, "Join Zense")))
    signuplink.click()
    ##############################

    ###### Third Account #########
    self.driver.find_element(By.ID, "email").send_keys("suzifreddie08@freddiemac.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Suzi1234=")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("Suzi1234=")
    self.driver.find_element(By.ID, "country_code").click()
    dropdown = self.driver.find_element(By.ID, "country_code")
    dropdown.find_element(By.XPATH, "//option[. = '(+1) US']").click()
    self.driver.find_element(By.ID, "phone_number").click()
    self.driver.find_element(By.ID, "phone_number").send_keys("(555) 555-5555")
    self.driver.find_element(By.ID, "registerForm").click()
    self.driver.find_element(By.NAME, "terms").click()
    self.driver.find_element(By.ID, "submit").click()
    # wait for element and click #
    signuplink = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.LINK_TEXT, "Join Zense")))
    signuplink.click()
    ##############################

    ###### Fourth Account #########
    self.driver.find_element(By.ID, "email").send_keys("alicefreddie08@freddiemac.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Alice1234=")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("Alice1234=")
    self.driver.find_element(By.ID, "country_code").click()
    dropdown = self.driver.find_element(By.ID, "country_code")
    dropdown.find_element(By.XPATH, "//option[. = '(+1) US']").click()
    self.driver.find_element(By.ID, "phone_number").click()
    self.driver.find_element(By.ID, "phone_number").send_keys("(777) 777-7777")
    self.driver.find_element(By.ID, "registerForm").click()
    self.driver.find_element(By.NAME, "terms").click()
    self.driver.find_element(By.ID, "submit").click()
    # wait for element and click #
    signuplink = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.LINK_TEXT, "Join Zense")))
    signuplink.click()
    ##############################

    ###### Fifth Account #########
    self.driver.find_element(By.ID, "email").send_keys("amyfreddie08@freddiemac.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Amy1234=")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("Amy1234=")
    self.driver.find_element(By.ID, "country_code").click()
    dropdown = self.driver.find_element(By.ID, "country_code")
    dropdown.find_element(By.XPATH, "//option[. = '(+1) US']").click()
    self.driver.find_element(By.ID, "phone_number").click()
    self.driver.find_element(By.ID, "phone_number").send_keys("(555) 222-1111")
    self.driver.find_element(By.ID, "registerForm").click()
    self.driver.find_element(By.NAME, "terms").click()
    self.driver.find_element(By.ID, "submit").click()
    # wait for element and click #
    signuplink = WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.LINK_TEXT, "Join Zense")))
    signuplink.click()
    ##############################
